apiVersion: v1
kind: Service
metadata:
  name: opa
spec:
  ports:
  - port: 8181
    targetPort: 8181
    name: http
  selector:
    app: opa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest
        ports:
        - containerPort: 8181
          name: http

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
data:
  policy.rego: |
    package example

    default allow = false

    allow {
      input.method = "GET"
    }

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
spec:
  rules:
  - host: auth.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opa
            port:
              number: 8181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
      - name: hydra
        image: oryd/hydra:latest
        ports:
        - containerPort: 4444
          name: public
        - containerPort: 4445
          name: admin

---
apiVersion: v1
kind: Service
metadata:
  name: hydra
spec:
  ports:
  - port: 4444
    targetPort: 4444
    name: public
  - port: 4445
    targetPort: 4445
    name: admin
  selector:
    app: hydra
